import streamlit as st
from datetime import datetime, date, time
import pytz
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO

# ============================================================
#   KONVERSI JAM LOKAL → UTC (WAJIB UNTUK HUMAN DESIGN)
# ============================================================

def to_utc(tanggal: date, jam: time, timezone: str = "Asia/Jakarta"):
    """
    Konversi tanggal & jam lokal (misal WIB) ke UTC.
    Human Design pakai waktu UTC buat hitungan posisi planet.
    """
    local_tz = pytz.timezone(timezone)
    dt_local = local_tz.localize(datetime.combine(tanggal, jam))
    dt_utc = dt_local.astimezone(pytz.utc)
    return dt_utc


# ============================================================
#   LOGIKA HITUNG HUMAN DESIGN SEDERHANA (MVP)
# ============================================================

def hitung_tipe(jam_str: str) -> str:
    h = int(jam_str.split(":")[0])
    if 6 <= h < 12:
        return "Projector"
    elif 12 <= h < 18:
        return "Generator"
    elif 18 <= h < 22:
        return "Manifesting Generator"
    elif 22 <= h or h < 2:
        return "Manifestor"
    else:
        return "Reflector"

def hitung_authority(date_str: str) -> str:
    d = int(date_str.split("-")[-1])
    if d % 5 == 0:
        return "Emotional"
    elif d % 3 == 0:
        return "Sacral"
    elif d % 2 == 0:
        return "Splenic"
    else:
        return "Ego"

def hitung_profile(date_str: str) -> str:
    bulan = int(date_str.split("-")[1])
    profiles = ["1/3", "2/4", "3/5", "4/6", "5/1", "6/2"]
    return profiles[(bulan - 1) % 6]

def insight_yosep(tipe: str) -> str:
    mapping = {
        "Generator": "Lo itu mesin energi hidup, Bos. Kalau lo happy, semua orang happy.",
        "Manifesting Generator": "Gerak cepat, adaptif, lompat-lompat tapi hasil selalu kenceng.",
        "Projector": "Lo itu pembaca manusia. Bukan tenaga, tapi arah.",
        "Manifestor": "Lo suka ngegas dulu, mikir belakangan. Wajar, energi lo emang buat mulai.",
        "Reflector": "Lo itu cermin hidup. Lingkungan bikin lo bersinar atau redup.",
    }
    return mapping.get(tipe, "Unik, beda, dan punya jalur sendiri.")


# ============================================================
#   BIKIN PDF PAKAI REPORTLAB (AMAN DI STREAMLIT)
# ============================================================

def buat_pdf_blueprint(nama: str,
                       kota: str,
                       utc_date_str: str,
                       utc_time_str: str,
                       tipe: str,
                       authority: str,
                       profile: str,
                       insight: str) -> bytes:

    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    margin = 50
    y = height - 60

    c.setFont("Helvetica-Bold", 18)
    c.drawString(margin, y, f"Blueprint Jiwa — {nama}")
    y -= 30

    c.setFont("Helvetica", 11)
    c.drawString(margin, y, f"Tanggal (UTC): {utc_date_str}")
    y -= 18
    c.drawString(margin, y, f"Jam (UTC): {utc_time_str}")
    y -= 18

    if kota:
        c.drawString(margin, y, f"Kota Lahir: {kota}")
        y -= 18

    y -= 12
    c.line(margin, y, width - margin, y)
    y -= 30

    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, "Ringkasan Blueprint")
    y -= 22

    c.setFont("Helvetica", 11)
    c.drawString(margin, y, f"Tipe: {tipe}")
    y -= 18
    c.drawString(margin, y, f"Authority: {authority}")
    y -= 18
    c.drawString(margin, y, f"Profile: {profile}")
    y -= 24

    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, "Insight Yosep Nurhandi:")
    y -= 22

    c.setFont("Helvetica", 11)
    max_w = width - 2 * margin
    words = insight.split()
    line = ""

    for w in words:
        test = (line + " " + w).strip()
        if c.stringWidth(test, "Helvetica", 11) < max_w:
            line = test
        else:
            c.drawString(margin, y, line)
            y -= 16
            line = w
    if line:
        c.drawString(margin, y, line)
        y -= 20

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(margin, 40, "Blueprint Jiwa — MVP | Autogenerated PDF.")

    c.showPage()
    c.save()

    return buffer.getvalue()


# ============================================================
#                    STREAMLIT APP
# ============================================================

st.set_page_config(page_title="Blueprint Jiwa — Quick Reader", page_icon="🔮")

st.title("🔮 Blueprint Jiwa — Quick Reader (MVP UTC)")
st.caption("Hitungan waktu dikonversi otomatis ke UTC — standar Human Design.")

st.write("Masukkan data lahir, terus klik **Proses Blueprint**.")

nama = st.text_input("Nama")

tanggal = st.date_input(
    "Tanggal Lahir",
    min_value=date(1950, 1, 1),
    max_value=date(2030, 12, 31),
    value=date(2000, 1, 1)
)

jam = st.time_input("Jam Lahir (waktu lokal, misal WIB)")
kota = st.text_input("Kota Lahir (opsional)")

if st.button("Proses Blueprint"):
    if not nama:
        st.warning("Isi nama dulu bos.")
    else:
        dt_utc = to_utc(tanggal, jam)
        utc_date_str = dt_utc.strftime("%Y-%m-%d")
        utc_time_str = dt_utc.strftime("%H:%M")

        tipe = hitung_tipe(utc_time_str)
        authority = hitung_authority(utc_date_str)
        profile = hitung_profile(utc_date_str)
        insight = insight_yosep(tipe)

        st.subheader(f"✨ Blueprint untuk {nama}")
        st.write(f"**Tipe:** {tipe}")
        st.write(f"**Authority:** {authority}")
        st.write(f"**Profile:** {profile}")
        st.write(f"**Insight Yosep-style:** {insight}")
        st.info(f"Perhitungan berdasarkan **UTC**: {utc_date_str} {utc_time_str}")

        pdf = buat_pdf_blueprint(
            nama, kota, utc_date_str, utc_time_str,
            tipe, authority, profile, insight
        )

        st.download_button(
            "📥 Download PDF Blueprint",
            data=pdf,
            file_name=f"Blueprint_{nama}.pdf",
            mime="application/pdf"
        )
